#AllCops:
#  # Include gemspec and Rakefile
##  Include:
##   - 'app/**/*.rb'
##   - 'config/**/*.rb'
##   - 'lib/**/*.rb'
##   - 'lib/**/*.rake'
##  Exclude:
##   - 'vendor/**/*'
##   - 'spec/**/*'
##   - 'db/*.rb'
##   - 'bin/**/*'
#  RunRailsCops: true
#  DisplayCopNames: true
#  StyleGiudeCopsOnly: true
#
## Style/Documentation:
##  Exlude:
##   - 'lib/**/version.rb'
#
# Metrics/LineLength:
#  Max: 100
#
# Metrics/MethodLength:
#  Max: 15
##
## Metrics/AbcSize:
##  Max: 20
##
## Style/BareCommentAnnotation:
##  Enabled: false
##
## Style/CommentAnnotation:
##  Enabled: false
##
## Style/RaiseArgs:
##  Enabled: false
##
## Style/StringLiterals:
##  Enabled: false
##